modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "linglens"
version = "${version}"
displayName = "LingLens"
authors = "lin-lin-miao"
description = '''
LingLens提供 离线玩家传送、性能监控、实体统计、聊天缓存、玩家查询 等实用功能。
LingLens provides practical features such as offline player teleportation, performance monitoring, entity statistics, chat caching, and player queries.
'''
#logoFile = ""

[[dependencies.linglens]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.linglens]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
